### ISSUE TITLE
Ragdoll Replication

### ISSUE THREAD

**Issue by Subtixx** [Cesio137/ALSReplicated#10]
**Detailed description of issue**
Ragdolling is not replicated

**Steps To Reproduce:**
1: Download repository
2: Open project
3: Set number of players to 2 and netmode to listen server
4: Press X on the "client"

**Expected Results:**
Same position on both clients

**Actual Results:**
Not the same position on both, teleportation when going out of ragdoll mode

**Image of the result**
![grafik](https://user-images.githubusercontent.com/20743379/100517150-0808b100-3189-11eb-9433-f07d9eb8fdc9.png)

**Comment by muhammadmadi** [comment]
thank u

**Comment by Cesio137** [comment]
@Subtixx @muhammadmadi I made some improvements to avoid lag, of course this will depend on the connection.
