### ISSUE TITLE
First Person Turn In Place Problem

### ISSUE THREAD

**Issue by wilberolive** [Cesio137/ALSReplicated#11]
Try running as a Listen Server, with both a server and a client player. Then on the client, hold down C to enter first person view. Now look down at your feet and start turning with the mouse. Notice the turn in place animation plays but it does not match the amount the character is turning. It looks fine on the server. It is just the client that is the problem.

**Comment by Cesio137** [comment]
I see that, but its not a big desync only a kind of delay ir ping.

Can you record a gif and Tell me more details?

**Comment by wilberolive** [comment]
I tried it on [0KNMDM's Blueprint version](https://github.com/0KNMDM/ALSReplicated), and although it has a lot of other problems, the first person turn in place appears to work better. I also tried it with the [dyanikoglu's C++ version](https://github.com/dyanikoglu/ALSV4_CPP) and it works correctly. So something is wrong in this Blueprint version.

This is what the server's character looks like. Notice the animation matches the turn rate without any sliding of the feet.
[https://streamable.com/k61jf7](https://streamable.com/k61jf7)

This is what the client's character looks like. Notice the animation lags behind and the feet slide.
[https://streamable.com/ybnpdn](https://streamable.com/ybnpdn)

**Comment by Cesio137** [comment]
@wilberolive  I'm sorry but I tested it constantly and this error doesn't happen, consider to try to revise any changes in your project. If your engine version is 4.26, wait until the epic launches the hotfix version for I update the project.

Sorry for the inconvenience
