### ISSUE TITLE
Other Mesh stuck during animation

### ISSUE THREAD

**Issue by Grogdunn** [Cesio137/ALSReplicated#17]
**Detailed description of issue**
With UE5 (tested on linux at the moment), I've imported your blueprint (stable version 4.4.3) ecc, but if i change mesh the mannequin doesn't do any animation anymore.

**Steps To Reproduce:**
1. Open your project with UE5 
1. In ALS_AnimMan_CharacterBP attach input "M" to flip flop
1. run the game
1. move (ok works)
1. press M to swith mesh
1. wait 10 sec (or move)
1. the mannequin stay stuck in a "frame" of animation

**Expected Results:**
Not happening :smile: the other mesh with same skeleton will continue moving

**Comment by Grogdunn** [comment]
Maybe: https://github.com/Hiro-KE/ALSReplicated/commit/fc3b66952c3e7a490d7b393ffdd41e009a4feaec this can solve, but I cannot know how to see "delta" for Unreal Projects to see what was done and what to merge. There are some tooling to do that?

**Comment by Cesio137** [comment]
> Maybe: [Hiro-KE@fc3b669](https://github.com/Hiro-KE/ALSReplicated/commit/fc3b66952c3e7a490d7b393ffdd41e009a4feaec) this can solve, but I cannot know how to see "delta" for Unreal Projects to see what was done and what to merge. There are some tooling to do that?

Sorry but the function that replicates the mesh change don't exist anymore

Since 4.25 or 4.26 that problam was happen and i didn't find a goot fix at all, sorry for that
