### ISSUE TITLE
Direction bug when jumping/crouching/rolling

### ISSUE THREAD

**Issue by apustovitovsky** [Cesio137/ALSReplicated#21]
When i turn in place at some angle and then jump or crouch in place, other players see that i do that with wrong Z rotation. Seems like this rotation is the direction of my last movement that i did before turning. The same issue with roll ability, my character doesn't roll to my facing direction, instead of this it rolls my last movement direction.

**Comment by Cesio137** [comment]
> When i turn in place at some angle and then jump or crouch in place, other players see that i do that with wrong Z rotation. Seems like this rotation is the direction of my last movement that i did before turning. The same issue with roll ability, my character doesn't roll to my facing direction, instead of this it rolls my last movement direction.

I got the part of rolling state but I can´t find the bug when crunch or jump, need a video showing this problam

**Comment by apustovitovsky** [comment]
https://user-images.githubusercontent.com/29402739/151161453-a8f3166f-ca6f-41c9-ad67-7782aa009010.MP4

**Comment by apustovitovsky** [comment]
> > When i turn in place at some angle and then jump or crouch in place, other players see that i do that with wrong Z rotation. Seems like this rotation is the direction of my last movement that i did before turning. The same issue with roll ability, my character doesn't roll to my facing direction, instead of this it rolls my last movement direction.
> 
> I got the part of rolling state and jump but I can´t find the bug when crunch, need a video showing this problam

attached video with this bug

**Comment by Cesio137** [comment]
> > > When i turn in place at some angle and then jump or crouch in place, other players see that i do that with wrong Z rotation. Seems like this rotation is the direction of my last movement that i did before turning. The same issue with roll ability, my character doesn't roll to my facing direction, instead of this it rolls my last movement direction.
> > 
> > 
> > I got the part of rolling state and jump but I can´t find the bug when crunch, need a video showing this problam
> 
> attached video with this bug

can you download the last version and test it again?

https://streamable.com/yo71vx

**Comment by Cesio137** [comment]
This bug is already fixed now
