### ISSUE TITLE
I found this problem in the process of using.

### ISSUE THREAD

**Issue by tguncle** [Cesio137/ALSReplicated#23]
![image](https://user-images.githubusercontent.com/39689863/155146549-26d4176e-9b0e-4635-a133-b53cdfe489a4.png)
![image](https://user-images.githubusercontent.com/39689863/155146644-2916a3a4-0cba-471b-97bd-f427fb0f021c.png)
I found this problem in the process of using. The picture is my setting, and the video is a problem. Finally, thank you for doing this！

https://user-images.githubusercontent.com/39689863/155146946-0ff4c86f-373a-4db6-90cb-695024e62114.mp4

**Comment by tguncle** [comment]
![image](https://user-images.githubusercontent.com/39689863/155149876-c6df038b-5a20-4f07-a8e4-2f70904b714f.png)
Single player mode will not be a problem

**Comment by Cesio137** [comment]
I just replicate the character and not the plataform. Basically it's happen because plataform's position between client and server is diferent.
