### ISSUE TITLE
Problem with turn in place

### ISSUE THREAD

**Issue by DavWiz** [Cesio137/ALSReplicated#24]
The turn in place will not display correctly in all modes,  
Edit: Apparently there are a lot of bugs with the ue5 version, it stays in T-Pose on the client side, the game breaks if you use ragdoll/roll and more stuff.

**Comment by erjfischer** [comment]
I've tested this with the latest version of ALSReplicated in UE5 and it doesn't seem to T Pose. Host on client side can turn in place correctly. However, the client's turn in place animations arent as smooth. Foot placement doesnt seem to update appropriately. They still turn, but it is not nearly as smooth / accurate. Could be a foot IK issue.

**Comment by Cesio137** [comment]
fixed
