### ISSUE TITLE
Error Roll on client

### ISSUE THREAD

**Issue by bikouz** [Cesio137/ALSReplicated#26]
Launch you project on "Client"

**Comment by bikouz** [comment]
This problem is present only since 4.5.3, not on 4.5.2.

**Comment by dubnyaka** [comment]
> This problem is present only since 4.5.3, not on 4.5.2.

![image](https://user-images.githubusercontent.com/37617597/175775281-f0d6ea74-c04c-449f-b4a5-f9c5eafb5d31.png)

The green arrows are where I removed the connection

This fixes the bug but most likely disables something

**Comment by dubnyaka** [comment]
> > This problem is present only since 4.5.3, not on 4.5.2.
> 
> ![image](https://user-images.githubusercontent.com/37617597/175775281-f0d6ea74-c04c-449f-b4a5-f9c5eafb5d31.png)
> 
> The green arrows are where I removed the connection
> 
> This fixes the bug but most likely disables something

Else you can use this BP from 4.5.2
![image](https://user-images.githubusercontent.com/37617597/175775448-86af7f7c-c399-4437-8ec0-bb376a071e4e.png)
