### ISSUE TITLE
Map not appearing

### ISSUE THREAD

**Issue by JittoJoseph** [Cesio137/ALSReplicated#27]
the main demo map file is not appearing in the editor when i take the pack in Unreal engine 4.27, any way to fix this?

**Comment by bikouz** [comment]
Yes you have to download the UE5 version, take the version of ue4

**Comment by Cesio137** [comment]
Right, I updated it because of ALS community had asked a lot for an update to ue5. I'll try to do the same in ue4

**Comment by ThunderGod13** [comment]
> 

Thanks
