### ISSUE TITLE
Fix : Release Ragdoll With Jump Action Input

### ISSUE THREAD

**Issue by bikouz** [Cesio137/ALSReplicated#28]
![1](https://user-images.githubusercontent.com/58881107/169649692-de32482d-6e40-417c-9978-3b3785c88a49.PNG)
![2](https://user-images.githubusercontent.com/58881107/169649695-0637e27f-51a3-45be-9256-37e944531a20.PNG)

**Comment by Cesio137** [comment]
Right I'll take a look more later

**Comment by Cesio137** [comment]
fixed
