### ISSUE TITLE
Sprinting backwards does not work correctly in multiplayer

### ISSUE THREAD

**Issue by MrGoatsy** [Cesio137/ALSReplicated#29]
It will look jumpy/laggy and on the other player their screen it looks like you are running forwards.

**Comment by erjfischer** [comment]
Yea that jumpy/laggy-ness is because somewhere with the change in direction when sprint is held isn't replicated. I'm hoping this wont be a difficult fix.

**Comment by SKD0007** [comment]
> Yea that jumpy/laggy-ness is because somewhere with the change in direction when sprint is held isn't replicated. I'm hoping this wont be a difficult fix.


hey did you fix this ?
