### ISSUE TITLE
Stretchy legs when tapping forward

### ISSUE THREAD

**Issue by MrGoatsy** [Cesio137/ALSReplicated#30]
Here is what I mean:
https://imgur.com/a/cv5pVTe

It also happens when you tap any other directional key really fast.

**Comment by JittoJoseph** [comment]
Is everyone else getting this bug?

**Comment by kariofillis** [comment]
Yes, i can reproduce it with UE5.0.2, running as standalone

**Comment by kariofillis** [comment]
Hacky fix, by smoothing the inputs:
https://blueprintue.com/blueprint/tq6art-p/

Probably there is a better one though inside the ALS itself.

**Comment by erjfischer** [comment]
I'm not getting this issue on my end. Latest release, latest UE5 version, standalone, listen server, etc. All looks good to me.

**Comment by renews** [comment]
Im also getting this.

**Comment by SKD0007** [comment]
It would be great to have ledge climb down and vault pas part of base setup.

**Comment by SKD0007** [comment]
> Here is what I mean: https://imgur.com/a/cv5pVTe
> 
> It also happens when you tap any other directional key really fast.

I am also getting this. how do I fix this ?

**Comment by SKD0007** [comment]
> Hacky fix, by smoothing the inputs: https://blueprintue.com/blueprint/tq6art-p/
> 
> Probably there is a better solution though inside the ALS itself.

Where do I past this ?

**Comment by SKD0007** [comment]
> Hacky fix, by smoothing the inputs: https://blueprintue.com/blueprint/tq6art-p/
> 
> Probably there is a better solution though inside the ALS itself.

Thank you. I had this problem and this fixed it.

**Comment by Cesio137** [comment]
fixed
