### ISSUE TITLE
Running backwards is bugged

### ISSUE THREAD

**Issue by Pr4etori4nGu4rd** [Cesio137/ALSReplicated#34]
In editor, 2 player, as client:
player 1 is pressing SHIFT and W, he runs backwards and it looks buggy
player 2 is seeing the character chaning direction and running (looks normal)

**Comment by Pr4etori4nGu4rd** [comment]
Just noticed same for walking to the sides ( pressing SHIFT and A or D)

**Comment by Cesio137** [comment]
fixed
