### ISSUE TITLE
UE4 - Roll Direction Broken.

### ISSUE THREAD

**Issue by Juricze** [Cesio137/ALSReplicated#35]
First of all I want to thank the author for his work in many things works great. But i have one issue what i cant solve myself.
Video demonstrate whats happened... If someone know where is problem... I am stuck... If i run root motion montage... The direction is broken too... If you turn you character with WSAD direction of roll and other root motion will corrent...
UE4 - Cesio137 ALS v4.4.6

Manual How to imitate.
1. Start as Client ( Listen Server and Standalone works well )
2. Rotation Mode: LookingDirection
3. Rotate Camera 180 degrees
4. Let the character turn to right position of camera direction
5. Roll or run another RootMotion Montage

[https://www.dropbox.com/s/j6dkyekfzr2hgyo/UE4Editor_IY9TQLb2e5.mp4?dl=0](url)

**Comment by Juricze** [comment]
> I was usig this and finally got fed of fixing it and moved on to https://github.com/dyanikoglu/ALS-Community its a plugin version. works well for me.

But its completely in c++. I know blueprints only.

**Comment by Cesio137** [comment]
fixed
