### ISSUE TITLE
AI snap turns when aiming and rotating to walk elsewhere

### ISSUE THREAD

**Issue by MrGoatsy** [Cesio137/ALSReplicated#38]
As can be seen in this video, the AI doesn't rotate smoothly when aiming, it just snaps to the direction it is going to walk in:
https://cdn.discordapp.com/attachments/221798778208780288/1065973803982782604/Desktop_2023.01.20_-_13.38.32.03.mp4

It doesn't do this when not aiming.

**Comment by Cesio137** [comment]
You can change the "Interp Speed" as in the image below or change the "control rotation" smoothly.

![image](https://github.com/Cesio137/ALSReplicated/assets/29849613/a0f18d13-beef-4946-86d9-602b9fc342af)
