### ISSUE TITLE
the character walks sideways. (-pending)

### ISSUE THREAD

**Issue by marcossaoleo** [Cesio137/ALSReplicated#5]
in "client", "SelectRotationMode_1" and "Rifle" the character walks sideways.

**Comment by Cesio137** [comment]
I did the tests and I didn't find the problem, if you can send me a video and a better description

**Comment by marcossaoleo** [comment]
https://youtu.be/PQ6A1jzejjQ

**Comment by marcossaoleo** [comment]
> Fiz os testes e não encontrei o problema, se você puder me enviar um vídeo e uma descrição melhor

https://youtu.be/PQ6A1jzejjQ

**Comment by marcossaoleo** [comment]
> I did the tests and I didn't find the problem, if you can send me a video and a better description

Play as Client (4 players)
https://youtu.be/wIVFEYQ8DbI

Play as Client Listen Server (4 players)
https://youtu.be/PQ6A1jzejjQ

**Comment by Cesio137** [comment]
Fixed and good luck now
