### ISSUE TITLE
Slow motion movement when sprinting

### ISSUE THREAD

**Issue by Nash32x** [Cesio137/ALSReplicated#6]
When using the code in the construction script of the ALS_Base character, a sudden slow motion movement can be seen when sprinting ( on any other client ) this happens with both looking and velocity direction 

steps to reproduce - Connect the construction script, then play with 2 clients ( make sure you can see both screens clearly ) start sprinting from client 1 , around the client 2 player . Then while sprinting quickly change the direction ( like immediately run backwards ) 

now on the client 2 screen you will be able to see that the client 1 player is running in slow motion

**Comment by Cesio137** [comment]
you only need to disable this in construct script

![image](https://user-images.githubusercontent.com/29849613/96465477-64c69280-11ff-11eb-835a-9e2a085eedfe.png)
